name: CI

on:
  push:
    branches: [ main, develop, zj-1 ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build com Maven
        run: mvn clean install

      - name: Executar Testes
        run: mvn test

      - name: Análise SonarQube
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: 'jose-ricardo-silveira'
          token: ${{ secrets.SONAR_TOKEN }}
